### ISSUE TITLE
Something seems to be missing

### ISSUE THREAD

**Issue by iampedropiedade** [concrete5/composer#47]
I'm not sure if I'm doing this correctly but something seems to be missing.

Documentation here https://documentation.concretecms.org/building-website-concretecms/3-install-concrete5/2-create-project-using-composer says:
`composer create-project -n concrete5/composer`
but the correct package seems to be:
`composer create-project -n concretecms/composer`

I run the composer command:
`composer create-project -n concretecms/composer .`
I then try to open the site and get this error:
`Warning: require(concrete/dispatcher.php): Failed to open stream: No such file or directory in /var/www/html/public/index.php on line 3
`

If I then run:
`composer install`
the site loads.
I add all the details for the installation, it starts to install but at some point it fails:

```
require_once(doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php): Failed to open stream: No such file or directory.
Trace:
#0 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php(69): Whoops\Run->handleError(2, 'require_once(do...', '/var/www/html/v...', 69) #1 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php(69): require_once() #2 /var/www/html/public/concrete/src/Database/EntityManagerConfigFactory.php(88): Doctrine\Common\Annotations\AnnotationRegistry::registerFile('doctrine/orm/li...') #3 /var/www/html/public/concrete/src/Database/EntityManagerConfigFactory.php(75): Concrete\Core\Database\EntityManagerConfigFactory->getMetadataDriverImpl() #4 /var/www/html/public/concrete/src/Database/EntityManagerFactory.php(56): Concrete\Core\Database\EntityManagerConfigFactory->getConfiguration() #5 /var/www/html/public/concrete/src/Database/DatabaseServiceProvider.php(79): Concrete\Core\Database\EntityManagerFactory->create(Object(Concrete\Core\Database\Connection\Connection)) #6 /var/www/html/vendor/illuminate/container/Container.php(873): Concrete\Core\Database\DatabaseServiceProvider->Concrete\Core\Database\{closure}(Object(Concrete\Core\Application\Application), Array) #7 /var/www/html/public/concrete/src/Application/Application.php(445): Illuminate\Container\Container->build(Object(Closure)) #8 /var/www/html/vendor/illuminate/container/Container.php(758): Concrete\Core\Application\Application->build(Object(Closure)) #9 /var/www/html/vendor/illuminate/container/Container.php(295): Illuminate\Container\Container->resolve('Doctrine\\ORM\\En...', Array, false) #10 /var/www/html/vendor/illuminate/container/Container.php(873): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Concrete\Core\Application\Application), Array) #11 /var/www/html/public/concrete/src/Application/Application.php(445): Illuminate\Container\Container->build(Object(Closure)) #12 /var/www/html/vendor/illuminate/container/Container.php(758): Concrete\Core\Application\Application->build(Object(Closure)) #13 /var/www/html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve('Doctrine\\ORM\\En...', Array) #14 /var/www/html/vendor/illuminate/container/Container.php(1027): Illuminate\Container\Container->make('Doctrine\\ORM\\En...') #15 /var/www/html/vendor/illuminate/container/Container.php(947): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #16 /var/www/html/vendor/illuminate/container/Container.php(908): Illuminate\Container\Container->resolveDependencies(Array) #17 /var/www/html/public/concrete/src/Application/Application.php(445): Illuminate\Container\Container->build('Concrete\\Core\\S...') #18 /var/www/html/vendor/illuminate/container/Container.php(292): Concrete\Core\Application\Application->build('Concrete\\Core\\S...') #19 /var/www/html/vendor/illuminate/container/Container.php(873): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Concrete\Core\Application\Application), Array) #20 /var/www/html/public/concrete/src/Application/Application.php(445): Illuminate\Container\Container->build(Object(Closure)) #21 /var/www/html/vendor/illuminate/container/Container.php(758): Concrete\Core\Application\Application->build(Object(Closure)) #22 /var/www/html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve('Concrete\\Core\\S...', Array) #23 /var/www/html/public/concrete/src/Support/Facade/Facade.php(118): Illuminate\Container\Container->make('site/type') #24 /var/www/html/public/concrete/src/Package/StartingPointPackage.php(613): Concrete\Core\Support\Facade\Facade::__callStatic('make', Array) #25 /var/www/html/public/concrete/src/Package/StartingPointPackage.php(184): Concrete\Core\Package\StartingPointPackage->install_site() #26 /var/www/html/public/concrete/controllers/Install.php(390): Concrete\Core\Package\StartingPointPackage->executeInstallRoutine('install_site') #27 [internal function]: Concrete\Controller\Install->run_routine('atomik_full', 'install_site') #28 /var/www/html/public/concrete/src/Controller/AbstractController.php(318): call_user_func_array(Array, Array) #29 /var/www/html/public/concrete/src/Routing/ControllerRouteAction.php(64): Concrete\Core\Controller\AbstractController->runAction('run_routine', Array) #30 /var/www/html/public/concrete/src/Http/RouteDispatcher.php(37): Concrete\Core\Routing\ControllerRouteAction->execute(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Routing\Route), Array) #31 /var/www/html/public/concrete/src/Http/Middleware/DispatcherDelegate.php(39): Concrete\Core\Http\RouteDispatcher->dispatch(Object(Concrete\Core\Http\Request)) #32 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareStack.php(86): Concrete\Core\Http\Middleware\DispatcherDelegate->next(Object(Concrete\Core\Http\Request)) #33 /var/www/html/public/concrete/src/Http/DefaultDispatcher.php(127): Concrete\Core\Http\Middleware\MiddlewareStack->process(Object(Concrete\Core\Http\Request)) #34 /var/www/html/public/concrete/src/Http/DefaultDispatcher.php(60): Concrete\Core\Http\DefaultDispatcher->handleDispatch(Object(Concrete\Core\Http\Request)) #35 /var/www/html/public/concrete/src/Http/Middleware/DispatcherDelegate.php(39): Concrete\Core\Http\DefaultDispatcher->dispatch(Object(Concrete\Core\Http\Request)) #36 /var/www/html/public/concrete/src/Http/Middleware/FrameOptionsMiddleware.php(39): Concrete\Core\Http\Middleware\DispatcherDelegate->next(Object(Concrete\Core\Http\Request)) #37 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareDelegate.php(50): Concrete\Core\Http\Middleware\FrameOptionsMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\DispatcherDelegate)) #38 /var/www/html/public/concrete/src/Http/Middleware/StrictTransportSecurityMiddleware.php(36): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request)) #39 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareDelegate.php(50): Concrete\Core\Http\Middleware\StrictTransportSecurityMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate)) #40 /var/www/html/public/concrete/src/Http/Middleware/ContentSecurityPolicyMiddleware.php(36): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request)) #41 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareDelegate.php(50): Concrete\Core\Http\Middleware\ContentSecurityPolicyMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate)) #42 /var/www/html/public/concrete/src/Http/Middleware/CookieMiddleware.php(35): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request)) #43 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareDelegate.php(50): Concrete\Core\Http\Middleware\CookieMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate)) #44 /var/www/html/public/concrete/src/Http/Middleware/ApplicationMiddleware.php(29): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request)) #45 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareDelegate.php(50): Concrete\Core\Http\Middleware\ApplicationMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate)) #46 /var/www/html/public/concrete/src/Http/Middleware/MiddlewareStack.php(86): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request)) #47 /var/www/html/public/concrete/src/Http/DefaultServer.php(85): Concrete\Core\Http\Middleware\MiddlewareStack->process(Object(Concrete\Core\Http\Request)) #48 /var/www/html/public/concrete/src/Foundation/Runtime/Run/DefaultRunner.php(125): Concrete\Core\Http\DefaultServer->handleRequest(Object(Concrete\Core\Http\Request)) #49 /var/www/html/public/concrete/src/Foundation/Runtime/DefaultRuntime.php(102): Concrete\Core\Foundation\Runtime\Run\DefaultRunner->run() #50 /var/www/html/public/concrete/dispatcher.php(45): Concrete\Core\Foundation\Runtime\DefaultRuntime->run() #51 /var/www/html/public/index.php(3): require('/var/www/html/p...') #52 {main}

```

I end up with 348 tables on the DB and a failed installation.
I've deleted all the tables and tried a couple of times, always the same error.

Am I missing anything?
Running this on Docker with PHP 8.2 and Mysql 8.

**Comment by mlocati** [comment]
This is a known issue (see https://github.com/concretecms/concretecms/issues/11130).
It [has already been fixed](https://github.com/concretecms/concretecms/pull/11185): this fix will be included in the (much awaited) upcoming ConcreteCMS version.

**Comment by iampedropiedade** [comment]
Thanks @mlocati 

I don't suppose there's a road map with planned release dates that you could point me to? Need to see if it's worth patching or if it's best to wait.

**Comment by mlocati** [comment]
That's a question for @aembler 😉

**Comment by aembler** [comment]
@iampedropiedade I've updated our roadmap page, which was pretty out of date. In general we're planning on releasing 9.2.0 very soon (a release candidate is imminent) - I will post the release for that shortly. Then after that there will be several maintenance releases for 9.2.0, and we're actually targeting 9.3.0 much more quickly than we might normally - by this summer or Fall.

**Comment by mlocati** [comment]
PS: the roadmap is available at https://github.com/concretecms/concretecms/milestones

**Comment by iampedropiedade** [comment]
> @iampedropiedade I've updated our roadmap page, which was pretty out of date. In general we're planning on releasing 9.2.0 very soon (a release candidate is imminent) - I will post the release for that shortly. Then after that there will be several maintenance releases for 9.2.0, and we're actually targeting 9.3.0 much more quickly than we might normally - by this summer or Fall.

Thanks!
